Vagrant.configure("2") do |config|
  
  Vagrantbox = 'centos'
  # Vagrantbox = 'deb'
  if "#{Vagrantbox}" == 'centos'
    VagrantBoxImage = 'centos/7'
  else
    VagrantBoxImage = 'peru/ubuntu-20.04-server-amd64'
  end

  # config.trigger.before :up do |trigger|
  #   trigger.name = "Hello world"
  #   trigger.info = "I am running before vagrant up!!"
  #   trigger.run =  {inline: "VBoxManage natnetwork add --netname k8snat  --network 192.168.4.0/24 --enable --dhcp on"}
  # end

  config.vm.define "LoadBalancer" do |lb|
    lb.vm.provider "virtualbox" do |lb|
      lb.memory = "1024"
      lb.cpus = 1
      lb.name = "LB-HA-Proxy"
      lb.gui = false
    end
    lb.vm.box = "#{VagrantBoxImage}"
    lb.vm.hostname = "LB-HA-Proxy" 
    lb.vm.provision "shell"  do |script|
      script.path = "Common.sh"
      script.args = "#{Vagrantbox}"
    end
    lb.vm.provision "shell", inline: <<-SHELL
    echo "nameserver 192.168.1.1" >/etc/resolv.conf
    >/etc/sysconfig/network-scripts/ifcfg-eth0
    cat >/etc/sysconfig/network-scripts/ifcfg-eth0<< EOF
    DEVICE="eth0"
    BOOTPROTO="static"
    ONBOOT="yes"
    TYPE="Ethernet"
    IPADDR=192.168.1.200
    NETMASK=255.255.255.0
    GATEWAY=192.168.1.1
EOF
    # shutdown -h now
    SHELL
    lb.trigger.after :halt do |trigger|
    trigger.name = "Running on halt vm"
    trigger.info = "Changing nic to briedge adaptor"
    trigger.run =  {inline: "VBoxManage modifyvm LB-HA-Proxy --nic1 bridged --nictype1 82545EM --bridgeadapter1 'Hyper-V Virtual Ethernet Adapter #2'"}
    end
  end

  (1..3).each do |i|
    config.vm.define "kubemaster#{i}" do |kubemaster|
      kubemaster.vm.provider "virtualbox" do |k|
        k.memory = 2048
        k.cpus = 2
        k.name = "kubemaster#{i}"
        k.gui = false
      end
      kubemaster.vm.box = "#{VagrantBoxImage}"
      kubemaster.vm.hostname = "kubemaster#{i}"
      kubemaster.vm.provision "shell"  do |script|
        script.path = "Common.sh"
        script.args = "#{Vagrantbox}"
      kubemaster.vm.provision "shell", inline: <<-SHELL
      echo "nameserver 192.168.1.1" >/etc/resolv.conf
      >/etc/sysconfig/network-scripts/ifcfg-eth0
      cat >>/etc/sysconfig/network-scripts/ifcfg-eth0<< EOF
      DEVICE="eth0"
      BOOTPROTO="static"
      ONBOOT="yes"
      TYPE="Ethernet"
      IPADDR=192.168.1.20#{i}
      NETMASK=255.255.255.0
      GATEWAY=192.168.1.1
EOF
      SHELL
      end
      kubemaster.trigger.after :halt do |trigger|
        trigger.name = "Running on halt vm"
        trigger.info = "Changing nic to briedge adaptor"
        trigger.run =  {inline: "VBoxManage modifyvm kubemaster#{i} --nic1 bridged --nictype1 82545EM --bridgeadapter1 'Hyper-V Virtual Ethernet Adapter #2'"}
        end
    end
  end
  (1..1).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.provider "virtualbox" do |w|
        w.name = "kubeworker#{i}"
        w.memory = "1024"
        w.cpus = "1"
        w.gui = false
      end
      worker.vm.box = "#{VagrantBoxImage}"
      worker.vm.hostname = "kubeworker#{i}"
      worker.vm.provision "shell"  do |script|
        script.path = "Common.sh"
        script.args = "#{Vagrantbox}"
      end
      worker.vm.provision "shell", inline: <<-SHELL
      echo "nameserver 192.168.1.1" >/etc/resolv.conf
      >/etc/sysconfig/network-scripts/ifcfg-eth0
      cat >>/etc/sysconfig/network-scripts/ifcfg-eth0<< EOF
      DEVICE="eth0"
      BOOTPROTO="static"
      ONBOOT="yes"
      TYPE="Ethernet"
      IPADDR=192.168.1.12{i}
      NETMASK=255.255.255.0
      GATEWAY=192.168.1.1
EOF
      SHELL
    end
      # worker.trigger.after :halt do |trigger|
      #   trigger.name = "Running on halt vm"
      #   trigger.info = "Changing nic to briedge adaptor"
      #   trigger.run =  {inline: "VBoxManage modifyvm kubeworker#{i} --nic1 bridged --nictype1 82545EM --bridgeadapter1 'Hyper-V Virtual Ethernet Adapter #2'"}
      #   end
  end
end