Vagrant.configure("2") do |config|
  
  # Vagrantbox = 'centos'
  Vagrantbox = 'deb'
  if "#{Vagrantbox}" == 'centos'
    VagrantBoxImage = 'centos/7'
  else
    VagrantBoxImage = 'peru/ubuntu-20.04-server-amd64'
  end

  config.vm.provision "shell"  do |script|
    script.path = "Common.sh"
    script.args = "#{Vagrantbox}"
  end
  config.vm.define "LoadBalancer" do |lb|
    lb.vm.provider "virtualbox" do |lb|
      lb.memory = 1024
      lb.cpus = 1
      lb.name = "LB-HA-Proxy"
      lb.gui = false
    end
    lb.vm.network "private_network", ip: "192.168.2.200"
    # lb.vm.network "forwarded_port", guest: 22, host: "2200"
    lb.vm.box = "#{VagrantBoxImage}"
    lb.vm.hostname = "LB-HA-Proxy"
    lb.vm.provision "shell", path: "provision_lb.sh"
  end
  
  (1..3).each do |i|
    config.vm.define "etcd#{i}" do |etcd|
      etcd.vm.provider "virtualbox" do |etcd|
        etcd.memory = 1024
        etcd.cpus = 1
        etcd.name = "ETCD#{i}"
        etcd.gui = false
      end
      etcd.vm.network "private_network", ip: "192.168.2.10#{i}"
      # kubemaster.vm.network "forwarded_port", guest: 22, host: "220#{i}"
      etcd.vm.box = "#{VagrantBoxImage}"
      etcd.vm.hostname = "ETCD#{i}"
    end
  end

  (1..3).each do |i|
    config.vm.define "kubemaster#{i}" do |kubemaster|
      kubemaster.vm.provider "virtualbox" do |kubemaster|
        kubemaster.memory = 2048
        kubemaster.cpus = 2
        kubemaster.name = "kubemaster#{i}"
        kubemaster.gui = false
      end
      kubemaster.vm.network "private_network", ip: "192.168.2.20#{i}"
      # kubemaster.vm.network "forwarded_port", guest: 22, host: "220#{i}"
      kubemaster.vm.box = "#{VagrantBoxImage}"
      kubemaster.vm.hostname = "kubemaster#{i}"
      # kubemaster.vm.provision "shell", path: "provision_master.sh"
    end
  end
  # (1..1).each do |i|
  #   config.vm.define "worker#{i}" do |worker|
  #     worker.vm.provider "virtualbox" do |worker|
  #       worker.name = "kubeworker#{i}"
  #       worker.memory = "1024"
  #       worker.cpus = "1"
  #       worker.gui = false
  #     end
  #     worker.vm.box = "#{VagrantBoxImage}"
  #     worker.vm.hostname = "kubeworker#{i}"
  #     worker.vm.network "private_network", ip: "192.168.2.2#{i}"
  #     worker.vm.network "forwarded_port", guest: 22, host: "232#{i}"
  #     worker.vm.provision "shell", path: "provision_worker.sh"
  #   end
  # end
end