Vagrant.configure("2") do |config|
  
  config.vm.provision "shell", path: "Common.sh"
  OS_RELEASE = 7
  config.vm.define "kubemaster" do |kubemaster|
    kubemaster.vm.provider "virtualbox" do |kubemaster|
      kubemaster.memory = 2048
      kubemaster.cpus = 2
      kubemaster.name = "kubemaster"
    end
    kubemaster.vm.network "private_network", ip: "192.168.2.200"
    kubemaster.vm.box = "centos/#{OS_RELEASE}"
    kubemaster.vm.hostname = "kubemaster"
    kubemaster.vm.provision "shell", path: "provision_master.sh"
  end

  (1..2).each do |i|
    config.vm.define "worker#{i}" do |worker|
      worker.vm.provider "virtualbox" do |worker|
        worker.name = "kubeworker#{i}"
        worker.memory = "1024"
        worker.cpus = "1"
      end
      worker.vm.box = "centos/#{OS_RELEASE}"
      worker.vm.hostname = "kubeworker#{i}"
      worker.vm.network "private_network", ip: "192.168.2.2#{i}"
      worker.vm.provision "shell", path: "provision_worker.sh"
    end
  end
end